### ISSUE TITLE
Update helm chart quorum-node using quorum-account-plugin using hashicorp vault

### ISSUE THREAD

**Issue by trmaphi** [FPT-Blockchain-Lab/helm-charts#23]
- [X] Run example from [docs](https://github.com/ConsenSys/quorum-account-plugin-hashicorp-vault/blob/master/docs/quickstart-example-quorum-signer.md)
- [x] Deploy hashicorp vault with secret engine on k8s
- [ ] Edit quorum-node helm-chart (stateful-set specifically) to use quorum-account-plugin

**Comment by bimow12** [comment]
https://github.com/FPT-Blockchain-Lab/helm-charts/tree/feature/quorum-account-plugin

**Comment by trmaphi** [comment]
@imtoanle review dùm e PR này với
